### ISSUE TITLE
Cannot decide the start and end of week

### ISSUE THREAD

**Issue by Thewisem** [JuliusHenke/Timetable-App#10]
I would like to add that I cannot decide the start of the week. If I choose monday only it will let me choose the end of the week. If I choose another day, the start and end would be on the same day. I can't choose sunday to friday or sunday to monday. Only sunday to sunday,saturday to saturday etc,. And It would really be helpful if you could have everything in it in landscape mode. Only the settings support landscape mode. :)

**Comment by JuliusHenke** [comment]
Hi, thanks for reporting that bug. I will have time in April to fix it and maybe add support for landscape mode.
If you got time and wanna implement it now, I am really happy to review and merge pull requests. 😊👍

**Comment by JuliusHenke** [comment]
@Thewisem I have added support for landscape mode in all screens. The update should roll out in a few days.

For the time being I will not change the way you can set the start and end of the week (limited time for this project). I suggest you just use the full week (Monday to Sunday) or open a pull request with your changes :)
