### ISSUE TITLE
Include your app with F-Droid?

### ISSUE THREAD

**Issue by IzzySoft** [JuliusHenke/Timetable-App#3]
Would you mind have your app included with F-Droid, the free and open source app "store"? I've [opened an RFP](https://gitlab.com/fdroid/rfp/issues/702) (Request For Packaging) for you, and hope you agree. If so, it would help if you could "tag" your releases, so updates can be easily detected.

**Comment by JuliusHenke** [comment]
Yes, we can include the app in F-Droid. How do I tag new releases? Do I need to take further steps?

**Comment by licaon-kter** [comment]
When you decide your app needs a new release, update versionCode and versionName, go to https://github.com/JuliusHenke/Timetable-App/releases and make a new release.

It's important to keep it consistent, eg. versionName is `2.2` then Tag is usually `2.2` too, or `v2.2`, but don't go overboard, eg. don't use suffixes in versionName.

**Comment by licaon-kter** [comment]
In the mean time, fix these errors:
```
:app:compileReleaseJavaWithJavac/home/user/fdroiddata-0907/build/juliushenke.smarttt/app/src/main/java/juliushenke/smarttt/SubjectActivity.java:65: error: cannot find symbol
        if(settings.isDarkDesign()) item.setIcon(R.drawable.ic_done_white_24dp);
                                                           ^
  symbol:   variable ic_done_white_24dp
  location: class drawable
/home/user/fdroiddata-0907/build/juliushenke.smarttt/app/src/main/java/juliushenke/smarttt/MainActivity.java:96: error: cannot find symbol
            if(settings.isDarkDesign()) item.setIcon(R.drawable.ic_done_white_24dp);
                                                               ^
  symbol:   variable ic_done_white_24dp
  location: class drawable
/home/user/fdroiddata-0907/build/juliushenke.smarttt/app/src/main/java/juliushenke/smarttt/MainActivity.java:99: error: cannot find symbol
            if(settings.isDarkDesign()) item.setIcon(R.drawable.ic_edit_white_24dp);
                                                               ^
  symbol:   variable ic_edit_white_24dp
  location: class drawable
```

**Comment by IzzySoft** [comment]
@JuliusHenke any chance for tags (and for getting that issue solved)? Or did you abandon this app meanwhile (as there were no commits for half a year)?

**Comment by JuliusHenke** [comment]
@IzzySoft The app is not under active development since it was more of a learning exercise for me personally. 
I didn't have much time for private projects recently. I still might be able to solve the issues and do the tags soon.

**Comment by IzzySoft** [comment]
Thanks @JuliusHenke – looking forward to that!

**Comment by JuliusHenke** [comment]
Hey @IzzySoft ,
I finally got time to release a version of the app which can be used for the F-Droid App Store.
Let me know if there are any issues.

**Comment by IzzySoft** [comment]
Thanks Julius! Unfortunately, there's indeed an issue: could it be you forgot to adjust versionCode and versionName? The tag iw `2.2`, but the app identifies as `2.1`.

I've for now added your app [to my repo](https://apt.izzysoft.de/fdroid/index/apk/juliushenke.smarttt) (that's a matter of minutes). As soon as everything is fixed, I'd update the RFP mentioned in my initial post so the app gets pulled into the official one.

**Comment by JuliusHenke** [comment]
@IzzySoft Ok, I have updated it now to the following: 
VersionCode=16
VersionName=2.2
Tag=2.2

**Comment by IzzySoft** [comment]
I couldn't figure were to find that in your code (above data is from the APK), so I have to go blindly by what you wrote and adjusted the RFP correspondingly. Thanks!

**Comment by licaon-kter** [comment]
@JuliusHenke Why did you delete the needed files: https://github.com/JuliusHenke/Timetable-App/commit/231a0cdf2bd153192f20a0ec7eef6b4af5a286ea#diff-39e7d8c00954e920b98e7636f0ac30b2 ?

**Comment by JuliusHenke** [comment]
@licaon-kter  Upps, good point ^^
I wanted to clean up the repo but in the process I removed a few important files. Now they should be back. Are there still any necessary files missing?

**Comment by licaon-kter** [comment]
fdroid checkupdate
```
DEBUG: fetch_real_name: Checking manifest at build/juliushenke.smarttt/app/src/main/AndroidManifest.xml
DEBUG: ...got autoname 'Timetable      //Single words ------------------------------------------------------------------'
```
Umm...

Pls fix this ^^^^ so I can merge https://gitlab.com/fdroid/fdroiddata/merge_requests/5248

**Comment by IzzySoft** [comment]
@JuliusHenke could you please tag the latest fix so we can build? [Pierre just asked for that](https://gitlab.com/fdroid/rfp/-/issues/702#note_377871852). Once a tag exists that covers it, he could include the metadata. Thanks!

**Comment by JuliusHenke** [comment]
@IzzySoft I hope it now works with the new release and tag: https://github.com/JuliusHenke/Timetable-App/releases/tag/2.3

**Comment by IzzySoft** [comment]
Wow, that was fast – thanks! I'll let Pierre know.
